config/routes.rb
Rails.application.routes.draw do
  resources :audioposts

  root                 'static_pages#home'
  get    'help'     => 'static_pages#help'
  get    'about'    => 'static_pages#about'
  get    'contact'  => 'static_pages#contact'
  get    'signup'   => 'users#new'
  get    'login'    => 'sessions#new'
  delete 'logout'   => 'sessions#destroy'
  delete 'close'    => 'sessions#end_session' if Rails.env.test?

  get 'auth/:provider/callback', to: 'sessions#fb_create'
  get 'auth/failure', to: redirect('/')

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,            only: [:new, :create, :fb_create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @audiopost = Audiopost.new
    end
  end

  def help
  end

  def contact
  end

  def about
  end

  def sendgrid
    render text: "SendGrid"
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Contact') %>
<h1>About</h1>
<p>
Box7 is a platform for audio creation and sharing
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Box7 about the application at the
  <a href="http://www.linhtinh.com/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on Box7 at the
  <a href="http://www.linhtinh/#help">SoundBox help section</a>.

</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <script>
        document.body.style.backgroundImage='none';
    </script>

    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>
    <div id="homepagediv">
        <div id="logindiv">
          <text1> Create your very own sound channel</text1><br>
          <a id="modal_trigger" href="#modal"><button class="btn-large btn-primary"> Login </button></a>

          <!-- = link_to "Login", login_path, class: "btn btn-large btn-primary" %> -->

          <h3>
            Or <%= link_to "Sign up", signup_path %>
          </h3>
        </div>

      <div id="modal" class="popupContainer" style="display:none;">
        <header class="popupHeader">
          <span class="header_title">Login</span>
          <span class="modal_close"><i class="fa fa-times"></i></span>
        </header>

        <section class="popupBody">
          <!-- Social Login -->
          <div class="social_login">
            <div class="">
              <!-- = link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %> -->

              <a href="/auth/facebook" class="social_box fb" id="sign_in">
                <span class="icon"><i class="fa fa-facebook"></i></span>
                <span class="icon_title">Sign in with Facebook</span>

              </a>

              <a href="#" class="social_box google">
                <span class="icon"><i class="fa fa-google-plus"></i></span>
                <span class="icon_title">Signin with Google</span>
              </a>
            </div>

            <div class="centeredText">
              <span>Or use your Email address</span>
            </div>

            <div class="action_btns">
              <div class="one_half"><a href="#" id="login_form" class="btn">Login</a></div>
              <div class="one_half last"><a href="#" id="register_form" class="btn">Sign up</a></div>
            </div>
          </div>

          <!-- Username & Password Login form -->
          <div class="user_login">
            <%= form_for(:session, url: sessions_path) do |f| %>

                <%= f.label :email %>
                <%= f.text_field :email %>

                <%= f.label :password %>
                <%= link_to "(forgot password)", new_password_reset_path %>

                <%= f.password_field :password %>
                <%= f.label :remember_me, class: "checkbox inline" do %>
                    <%= f.check_box :remember_me %>
                    <span>Remember me on this computer</span>
                <% end %>
                <div class="action_btns">
                    <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                    <div class="one_half last"><%= f.submit "Log in", class: "btn btn-red" %></div>
                </div>
            <% end %>
            <!--
            <form>
              <label>Email / Username</label>
              <input type="text" />
              <br />

              <label>Password</label>
              <input type="password" />
              <br />

              <div class="checkbox">
                <input id="remember" type="checkbox" />
                <label for="remember">Remember me on this computer</label>
              </div>

              <div class="action_btns">
                <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                <div class="one_half last"><a href="#" class="btn btn_red">Login</a></div>
              </div>
            </form>
             -->
          </div>

          <!-- Register Form -->
          <div class="user_register">

            <%= form_for(:user, url: users_path) do |f| %>
                <!-- = render 'shared/error_messages', object: f.object %> -->

                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>

                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>

                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>

                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>

                <div class="action_btns">
                  <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                  <div class="one_half last"><%= f.submit "Register", class: "btn btn-primary" %></div>
                </div>
            <% end %>
            <!--
            <form>
              <label>Full Name</label>
              <input type="text" />
              <br />

              <label>Email Address</label>
              <input type="email" />
              <br />

              <label>Password</label>
              <input type="password" />
              <br />

              <div class="checkbox">
                <input id="send_updates" type="checkbox" />
                <label for="send_updates">Send me occasional email updates</label>
              </div>

              <div class="action_btns">
                <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                <div class="one_half last"><a href="#" class="btn btn_red">Register</a></div>
              </div>
            </form>
            -->
          </div>
        </section>
      </div>

      <script type="text/javascript">
          $("#modal_trigger").leanModal({top : 200, overlay : 0.6, closeButton: ".modal_close" });

          $(function(){
              // Calling Login Form
              $("#login_form").click(function(){
                  $(".social_login").hide();
                  $(".user_login").show();
                  return false;
              });

              // Calling Register Form
              $("#register_form").click(function(){
                  $(".social_login").hide();
                  $(".user_register").show();
                  $(".header_title").text('Register');
                  return false;
              });

              // Going back to Social Forms
              $(".back_btn").click(function(){
                  $(".user_login").hide();
                  $(".user_register").hide();
                  $(".social_login").show();
                  $(".header_title").text('Login');
                  return false;
              });
          })
      </script>


      <!--
              <div id="listen_container">
                <p align="center"> Most listened channels of the week</p>
                <div id="most_listened">

                </div>
              </div>
       -->
    </div>
<% end %>