config/routes.rb
Rails.application.routes.draw do
  resources :audioposts

  root                 'static_pages#home'
  get    'help'     => 'static_pages#help'
  get    'about'    => 'static_pages#about'
  get    'contact'  => 'static_pages#contact'
  get    'signup'   => 'users#new'
  get    'login'    => 'sessions#new'
  delete 'logout'   => 'sessions#destroy'
  delete 'close'    => 'sessions#end_session' if Rails.env.test?

  get 'auth/:provider/callback', to: 'sessions#fb_create'
  get 'auth/failure', to: redirect('/')

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,            only: [:new, :create, :fb_create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/audiopost.rb
class Audiopost < ActiveRecord::Base
end

app/controllers/audioposts_controller.rb
class AudiopostsController < ApplicationController
  before_action :set_audiopost, only: [:show, :edit, :update, :destroy]

  # GET /audioposts
  # GET /audioposts.json
  def index
    @audioposts = Audiopost.all
  end

  # GET /audioposts/1
  # GET /audioposts/1.json
  def show
  end

  # GET /audioposts/new
  def new
    @audiopost = Audiopost.new
  end

  # GET /audioposts/1/edit
  def edit
  end

  # POST /audioposts
  # POST /audioposts.json
  def create
    @audiopost = Audiopost.new(audiopost_params)

    respond_to do |format|
      if @audiopost.save
        format.html { redirect_to @audiopost, notice: 'Audiopost was successfully created.' }
        format.json { render :show, status: :created, location: @audiopost }
      else
        format.html { render :new }
        format.json { render json: @audiopost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audioposts/1
  # PATCH/PUT /audioposts/1.json
  def update
    respond_to do |format|
      if @audiopost.update(audiopost_params)
        format.html { redirect_to @audiopost, notice: 'Audiopost was successfully updated.' }
        format.json { render :show, status: :ok, location: @audiopost }
      else
        format.html { render :edit }
        format.json { render json: @audiopost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audioposts/1
  # DELETE /audioposts/1.json
  def destroy
    @audiopost.destroy
    respond_to do |format|
      format.html { redirect_to audioposts_url, notice: 'Audiopost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audiopost
      @audiopost = Audiopost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audiopost_params
      params[:audiopost]
    end
end

app/helpers/audioposts_helper.rb
module AudiopostsHelper
end

app/views/audioposts/_form.html.erb
<%= form_for(@audiopost) do |f| %>
  <% if @audiopost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audiopost.errors.count, "error") %> prohibited this audiopost from being saved:</h2>

      <ul>
      <% @audiopost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/audioposts/edit.html.erb
<h1>Editing audiopost</h1>

<%= render 'form' %>

<%= link_to 'Show', @audiopost %> |
<%= link_to 'Back', audioposts_path %>

app/views/audioposts/index.html.erb
<h1>Listing audioposts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @audioposts.each do |audiopost| %>
      <tr>
        <td><%= link_to 'Show', audiopost %></td>
        <td><%= link_to 'Edit', edit_audiopost_path(audiopost) %></td>
        <td><%= link_to 'Destroy', audiopost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audiopost', new_audiopost_path %>

app/views/audioposts/new.html.erb
<h1>New audiopost</h1>

<%= render 'form' %>

<%= link_to 'Back', audioposts_path %>

app/views/audioposts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_audiopost_path(@audiopost) %> |
<%= link_to 'Back', audioposts_path %>