config/routes.rb
Rails.application.routes.draw do
  resources :audioposts

  root                 'static_pages#home'
  get    'help'     => 'static_pages#help'
  get    'about'    => 'static_pages#about'
  get    'contact'  => 'static_pages#contact'
  get    'signup'   => 'users#new'
  get    'login'    => 'sessions#new'
  delete 'logout'   => 'sessions#destroy'
  delete 'close'    => 'sessions#end_session' if Rails.env.test?

  get 'auth/:provider/callback', to: 'sessions#fb_create'
  get 'auth/failure', to: redirect('/')

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,            only: [:new, :create, :fb_create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About us",   about_path %></li>
      <li><a href="#">Mobile app</a></li>
      <li><%= link_to "Help", help_path %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--<header class="navbar navbar-fixed-top navbar-inverse"> -->
<header class="navbar">
  <div class="container">
    <a href=<%=root_path%>> <div id='box7'></div></a>
    <!-- = link_to "<div id='box7'></div>", root_path, id: "logo" %> -->
    <nav>
      <ul class="nav navbar-nav pull-right">

        <form id="searchbox">
          <span><input type="text" class="search rounded" placeholder="Search..."></span>
        </form>


        <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
         <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>

<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<!-- onload="setupRecorder()" -->
<!-- div class="allbody"> -->
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="mainbody">

      <%= yield %>
    </div>
      <%= render 'layouts/footer' %>
      <%=  debug(params) if Rails.env.development? %>
  </div>
<!--/div> -->
</body>
</html>